/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'canmv_k210'}],
  newSidebar: [{type: 'autogenerated', dirName: 'canmv_k230'}],
  CyberCAMSidebar: [{type: 'autogenerated', dirName: 'cybercam'}],
  pyDroneSidebar: [{type: 'autogenerated', dirName: 'pydrone'}],
  pyControllerSidebar: [{type: 'autogenerated', dirName: 'pycontroller'}],
  pyCarSidebar: [{type: 'autogenerated', dirName: 'pycar'}],
  pyClockSidebar: [{type: 'autogenerated', dirName: 'pyclock'}],
  pyboardSidebar: [{type: 'autogenerated', dirName: 'pyboard'}],
  columbusSidebar: [{type: 'autogenerated', dirName: 'columbus'}],
  magellanSidebar: [{type: 'autogenerated', dirName: 'magellan'}],
  pyWiFi_ESP32_S3Sidebar: [{type: 'autogenerated', dirName: 'pywifi_esp32_s3'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
